export const COLOUR_CONFIG = {
  cool_blue: {
    bg: 'bg-blue-500',
    bgLight: 'bg-blue-50',
    bgMed: 'bg-blue-100',
    text: 'text-blue-700',
    textDark: 'text-blue-800',
    border: 'border-blue-300',
    ring: 'ring-blue-500/30',
    fill: 'bg-blue-500',
    hex: '#3b82f6',
    emoji: '🔵',
    gradient: 'from-blue-400 to-blue-600',
    softGradient: 'from-blue-50 to-blue-100/60',
    // Hero banner: deep enough that white text clears WCAG AA.
    hero: 'from-blue-700 to-blue-900',
    heroFg: 'text-white',
    heroFgSoft: 'text-white/90',
    heroChip: 'bg-white/10 ring-white/20',
    // Solid fill + legible label for buttons/pills (WCAG AA on the fill).
    solid: 'bg-blue-600',
    solidFg: 'text-white',
  },
  earth_green: {
    bg: 'bg-green-500',
    bgLight: 'bg-green-50',
    bgMed: 'bg-green-100',
    text: 'text-green-700',
    textDark: 'text-green-800',
    border: 'border-green-300',
    ring: 'ring-green-500/30',
    fill: 'bg-green-500',
    hex: '#22c55e',
    emoji: '🟢',
    gradient: 'from-green-400 to-green-600',
    softGradient: 'from-green-50 to-green-100/60',
    hero: 'from-green-700 to-green-900',
    heroFg: 'text-white',
    heroFgSoft: 'text-white/90',
    heroChip: 'bg-white/10 ring-white/20',
    solid: 'bg-green-700',
    solidFg: 'text-white',
  },
  sunshine_yellow: {
    bg: 'bg-yellow-400',
    bgLight: 'bg-yellow-50',
    bgMed: 'bg-yellow-100',
    text: 'text-yellow-700',
    textDark: 'text-yellow-800',
    border: 'border-yellow-300',
    ring: 'ring-yellow-400/30',
    fill: 'bg-yellow-400',
    hex: '#eab308',
    emoji: '🟡',
    gradient: 'from-yellow-300 to-yellow-500',
    softGradient: 'from-yellow-50 to-yellow-100/60',
    // Yellow is too light for white text — keep it bright and use near-black text.
    hero: 'from-yellow-300 to-yellow-500',
    heroFg: 'text-yellow-950',
    heroFgSoft: 'text-yellow-950/80',
    heroChip: 'bg-yellow-950/10 ring-yellow-950/20',
    // Bright yellow fill needs dark ink, not white (9.5:1 vs 1.5:1).
    solid: 'bg-yellow-400',
    solidFg: 'text-yellow-950',
  },
  fiery_red: {
    bg: 'bg-red-500',
    bgLight: 'bg-red-50',
    bgMed: 'bg-red-100',
    text: 'text-red-700',
    textDark: 'text-red-800',
    border: 'border-red-300',
    ring: 'ring-red-500/30',
    fill: 'bg-red-500',
    hex: '#ef4444',
    emoji: '🔴',
    gradient: 'from-red-400 to-red-600',
    softGradient: 'from-red-50 to-red-100/60',
    hero: 'from-red-600 to-red-800',
    heroFg: 'text-white',
    heroFgSoft: 'text-white/90',
    heroChip: 'bg-white/10 ring-white/20',
    solid: 'bg-red-600',
    solidFg: 'text-white',
  },
};

export function colourConfig(key) {
  return COLOUR_CONFIG[key] || COLOUR_CONFIG['cool_blue'];
}
