import { computeScores, generateReport } from './scoring'
import { createInitialState } from './storage'

/**
 * Local development helpers for working on signed-in views.
 *
 * The Profile view's share section, and anything else gated on `user`, can't
 * be exercised on localhost: Google OAuth only redirects to the deployed
 * domain, and the Express backend isn't running. This stubs the session so
 * those views can be built and reviewed offline.
 *
 * ── Why this cannot reach production ──────────────────────────────────────
 * `import.meta.env.DEV` is statically `false` during `vite build`, so every
 * branch below is dead code and Rollup strips it — the fake user never even
 * appears in the bundle. On top of that it needs an explicit opt-in
 * (`VITE_DEV_AUTH=1`), so simply running `npm run dev` does not bypass auth.
 * Both conditions must hold. Verified by grepping the production bundle.
 */
export const DEV_AUTH = import.meta.env.DEV && import.meta.env.VITE_DEV_AUTH === '1'

const SIGNED_IN_KEY = 'csp_dev_signed_in'
const SHARE_TOKEN_KEY = 'csp_dev_share_token'

/** The stand-in account. Obviously fake, so it can't be mistaken for real data. */
export const DEV_USER = {
  id: 0,
  name: 'Dev Tester',
  email: 'dev@localhost',
  avatarUrl: null,
  // Backdated so "member since" style copy has something realistic to show.
  createdAt: new Date(Date.now() - 34 * 86400000).toISOString(),
}

export function isDevSignedIn() {
  if (!DEV_AUTH) return false
  try {
    // Default to signed in — the whole point is reaching signed-in views.
    return localStorage.getItem(SIGNED_IN_KEY) !== 'false'
  } catch {
    return true
  }
}

export function setDevSignedIn(signedIn) {
  try {
    localStorage.setItem(SIGNED_IN_KEY, signedIn ? 'true' : 'false')
  } catch {
    // Storage unavailable — the toggle just won't persist across reloads.
  }
}

/* ── Stubbed share link, so create/copy/revoke can be exercised ─────────── */

export function devGetShareToken() {
  try {
    return localStorage.getItem(SHARE_TOKEN_KEY)
  } catch {
    return null
  }
}

export function devCreateShareToken() {
  const token = devGetShareToken() || `dev-${Math.random().toString(36).slice(2, 10)}`
  try {
    localStorage.setItem(SHARE_TOKEN_KEY, token)
  } catch {
    // Non-persistent, still returned so the UI can render.
  }
  return token
}

export function devRevokeShareToken() {
  try {
    localStorage.removeItem(SHARE_TOKEN_KEY)
  } catch {
    // Nothing to clean up.
  }
  return true
}

/**
 * A completed assessment, generated by answering the real questionnaire and
 * running the real scoring engine — not hand-written fixture data. That means
 * demo profiles exercise the same code path a real user does, so a scoring or
 * report bug shows up here too.
 *
 * `lean` biases answers toward one colour so the profile is clearly
 * differentiated rather than flat.
 */
export function buildDemoState(db, lean = 'cool_blue') {
  const responses = {}

  db.questionnaire.items.forEach(item => {
    if (item.type === 'likert_1_5') {
      // Agree strongly where the item maps to the chosen colour, mildly otherwise.
      const weight = item.maps_to?.[lean] ?? 0
      responses[item.id] = weight > 0 ? 5 : 2
    } else {
      // Pick whichever option maps to the chosen colour; fall back to A.
      const match = Object.keys(item.choices || {}).find(k => (item.choices[k]?.[lean] ?? 0) > 0)
      responses[item.id] = match || 'A'
    }
  })

  const scores = computeScores(responses, db)
  const report = generateReport(scores, db)

  return {
    ...createInitialState(),
    view: 'profile',
    responses,
    scores,
    report,
    assessmentComplete: true,
    reportRead: true,
    gamification: {
      ...createInitialState().gamification,
      xp: 750,
      level: 2,
      badges: ['badge_profile_complete'],
      tier: 'tier_explorer',
    },
  }
}
